-- ============================================
-- Receipt Tracker Database Schema
-- ============================================
-- This script creates all tables, indexes, and seed data
-- for the Receipt Tracker application.

-- ============================================
-- 1. USERS TABLE
-- ============================================
-- Note: This table is managed by Supabase Auth
-- Reference: auth.users

-- ============================================
-- 2. CATEGORIES TABLE
-- ============================================

CREATE TABLE public.categories (
  category_id BIGSERIAL NOT NULL,
  name VARCHAR(50) NOT NULL,
  description VARCHAR(255),
  bls_series_id VARCHAR(50),
  CONSTRAINT categories_pkey PRIMARY KEY (category_id),
  CONSTRAINT categories_name_key UNIQUE (name)
) TABLESPACE pg_default;

-- Seed data for categories
INSERT INTO public.categories (category_id, name, description, bls_series_id) VALUES
(1, 'Food and Beverages', 'Groceries, restaurants, alcohol, etc.', 'CUUR0000SAF'),
(2, 'Housing', 'Rent, utilities, furnishings, etc.', 'CUUR0000SAH'),
(3, 'Apparel', 'Clothing and footwear', 'CUUR0000SAA'),
(4, 'Transportation', 'Gas, car payments, public transport', 'CUUR0000SAT'),
(5, 'Medical Care', 'Healthcare, drugs, insurance', 'CUUR0000SAM'),
(6, 'Recreation', 'Entertainment, hobbies, pets', 'CUUR0000SAR'),
(7, 'Education and Communication', 'Tuition, books, internet, phone', 'CUUR0000SAE'),
(8, 'Other Goods and Services', 'Personal care, insurance, misc', 'CUUR0000SAG')
ON CONFLICT (category_id) DO NOTHING;

-- ============================================
-- 3. RECEIPTS TABLE
-- ============================================

CREATE TABLE public.receipts (
  receipt_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id BIGINT NOT NULL,
  store_name VARCHAR(255),
  purchase_date DATE DEFAULT CURRENT_DATE,
  category_id BIGINT,
  amount NUMERIC(10, 2) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  image_key VARCHAR(500),
  CONSTRAINT receipts_pkey PRIMARY KEY (receipt_id),
  CONSTRAINT receipts_receipt_id_key UNIQUE (receipt_id),
  CONSTRAINT receipts_category_id_fkey FOREIGN KEY (category_id) 
    REFERENCES categories (category_id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT receipts_user_id_fkey FOREIGN KEY (user_id) 
    REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE
) TABLESPACE pg_default;

-- Indexes for receipts
CREATE INDEX IF NOT EXISTS idx_receipts_user_date 
  ON public.receipts USING btree (user_id, purchase_date DESC) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_receipts_user_category 
  ON public.receipts USING btree (user_id, category_id) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_receipts_user_created 
  ON public.receipts USING btree (user_id, created_at DESC) TABLESPACE pg_default;

-- ============================================
-- 4. RECEIPT ITEMS TABLE
-- ============================================

CREATE TABLE public.receipt_items (
  receipt_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  receipt_id BIGINT NOT NULL,
  item_name VARCHAR(255) NOT NULL,
  quantity INTEGER DEFAULT 1,
  unit_price NUMERIC(10, 2),
  CONSTRAINT receipt_items_pkey PRIMARY KEY (receipt_item_id),
  CONSTRAINT receipt_items_receipt_id_fkey FOREIGN KEY (receipt_id) 
    REFERENCES receipts (receipt_id) ON UPDATE CASCADE ON DELETE CASCADE
) TABLESPACE pg_default;

-- Indexes for receipt items
CREATE INDEX IF NOT EXISTS idx_receipt_items_receipt_id 
  ON public.receipt_items USING btree (receipt_id) TABLESPACE pg_default;

-- ============================================
-- 5. PERSONAL CPI MONTHLY TABLE
-- ============================================

CREATE TABLE public.personal_cpi_monthly (
  id BIGSERIAL NOT NULL,
  user_id BIGINT NOT NULL,
  year INTEGER NOT NULL,
  month INTEGER NOT NULL,
  category_id BIGINT,
  total_spending NUMERIC(10, 2) NOT NULL,
  mom_change_percent NUMERIC(5, 2),
  yoy_change_percent NUMERIC(5, 2),
  calculated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
  CONSTRAINT personal_cpi_monthly_pkey PRIMARY KEY (id),
  CONSTRAINT personal_cpi_monthly_user_id_year_month_category_id_key 
    UNIQUE (user_id, year, month, category_id),
  CONSTRAINT personal_cpi_monthly_category_id_fkey FOREIGN KEY (category_id) 
    REFERENCES categories (category_id),
  CONSTRAINT personal_cpi_monthly_user_id_fkey FOREIGN KEY (user_id) 
    REFERENCES users (id)
) TABLESPACE pg_default;

-- Indexes for personal CPI
CREATE INDEX IF NOT EXISTS idx_personal_cpi_monthly 
  ON public.personal_cpi_monthly USING btree (user_id, year, month) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_personal_cpi_category 
  ON public.personal_cpi_monthly USING btree (user_id, category_id, year, month) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_personal_cpi_lookup 
  ON public.personal_cpi_monthly USING btree (user_id, year, month, category_id) TABLESPACE pg_default;

-- ============================================
-- 6. OFFICIAL CPI DATA TABLE
-- ============================================

CREATE TABLE public.official_cpi_data (
  id BIGSERIAL NOT NULL,
  year INTEGER NOT NULL,
  month INTEGER NOT NULL,
  category_id BIGINT,
  index_value NUMERIC(10, 3) NOT NULL,
  mom_change_percent NUMERIC(5, 2),
  yoy_change_percent NUMERIC(5, 2),
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
  CONSTRAINT official_cpi_data_pkey PRIMARY KEY (id),
  CONSTRAINT official_cpi_data_year_month_category_id_key 
    UNIQUE (year, month, category_id),
  CONSTRAINT official_cpi_data_category_id_fkey FOREIGN KEY (category_id) 
    REFERENCES categories (category_id)
) TABLESPACE pg_default;

-- Indexes for official CPI
CREATE INDEX IF NOT EXISTS idx_official_cpi_date 
  ON public.official_cpi_data USING btree (year, month) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_official_cpi_category 
  ON public.official_cpi_data USING btree (category_id, year, month) TABLESPACE pg_default;