AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Receipt Processing Lambda with SQS Queue

Resources:
  # Dead Letter Queue for failed messages
  ReceiptProcessingDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: receipt-processing-dlq
      MessageRetentionPeriod: 1209600  # 14 days
      
  # Main processing queue
  ReceiptProcessingQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: receipt-processing-queue
      VisibilityTimeout: 30
      MessageRetentionPeriod: 1209600  # 14 days
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt ReceiptProcessingDLQ.Arn
        maxReceiveCount: 3  # Move to DLQ after 3 failed attempts

  # Lambda function
  ReceiptProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: PersonalCPI.PersonalCPI.lambda.ReceiptLambdaHandler::handleRequest
      Runtime: java21
      CodeUri: build/libs/personal-cpi-backend-0.0.1-SNAPSHOT-all.jar
      MemorySize: 1024
      Timeout: 60
      Environment:
        Variables:
          RECEIPT_QUEUE_URL: !Ref ReceiptProcessingQueue
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - textract:AnalyzeExpense
              Resource: '*'
        - Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
              Resource: 'arn:aws:s3:::personal-cpi-receipts/*'
        - Statement:
            - Effect: Allow
              Action:
                - sqs:SendMessage
              Resource: !GetAtt ReceiptProcessingQueue.Arn

Outputs:
  ReceiptProcessorFunctionArn:
    Description: ARN of the Receipt Processor Lambda Function
    Value: !GetAtt ReceiptProcessorFunction.Arn
    
  ReceiptQueueUrl:
    Description: URL of the Receipt Processing Queue
    Value: !Ref ReceiptProcessingQueue
    Export:
      Name: ReceiptProcessingQueueUrl
      
  ReceiptQueueArn:
    Description: ARN of the Receipt Processing Queue
    Value: !GetAtt ReceiptProcessingQueue.Arn
    Export:
      Name: ReceiptProcessingQueueArn
      
  DLQUrl:
    Description: URL of the Dead Letter Queue
    Value: !Ref ReceiptProcessingDLQ
